/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/websocket_debug": {
    /** Websocket Debug */
    get: operations["websocket_debug_websocket_debug_get"];
  };
  "/files": {
    /** Files */
    get: operations["files_files_get"];
  };
  "/play/{file_id}": {
    /** Play */
    post: operations["play_play__file_id__post"];
  };
  "/download/{file_id}": {
    /** Download */
    get: operations["download_download__file_id__get"];
  };
  "/pause": {
    /** Pause */
    post: operations["pause_pause_post"];
  };
  "/next": {
    /** Next */
    post: operations["next__next_post"];
  };
  "/previous": {
    /** Previous */
    post: operations["previous_previous_post"];
  };
  "/add/{file_id}": {
    /** Add */
    post: operations["add_add__file_id__post"];
  };
  "/stop": {
    /** Stop */
    post: operations["stop_stop_post"];
  };
  "/clear": {
    /** Clear */
    post: operations["clear_clear_post"];
  };
  "/duration": {
    /** Duration */
    get: operations["duration_duration_get"];
  };
  "/state": {
    /** State */
    get: operations["state_state_get"];
  };
  "/file/{request_file_id}": {
    /** Upload File */
    post: operations["upload_file_file__request_file_id__post"];
  };
  "/meta/og-title/{website}": {
    /** Get Og Title */
    get: operations["get_og_title_meta_og_title__website__get"];
  };
  "/upload_from_url/{request_file_id}/{website}": {
    /** Upload From Url */
    post: operations["upload_from_url_upload_from_url__request_file_id___website__post"];
  };
  "/file/{file_id}": {
    /** Delete File */
    delete: operations["delete_file_file__file_id__delete"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Body_upload_file_file__request_file_id__post */
    Body_upload_file_file__request_file_id__post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** File */
    File: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Location
       * Format: path
       */
      location: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * State
     * @description States the player can be in.
     * @enum {string}
     */
    State: "initiated" | "opening" | "buffering" | "playing" | "paused" | "stopped" | "ended" | "error";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * Event
     * @description Events the player emits when an event occurs.
     * @enum {string}
     */
    Event: "statechange" | "filechange" | "volumechange" | "error";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Websocket Debug */
  websocket_debug_websocket_debug_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Files */
  files_files_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: components["schemas"]["File"];
          };
        };
      };
    };
  };
  /** Play */
  play_play__file_id__post: {
    parameters: {
      path: {
        file_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Download */
  download_download__file_id__get: {
    parameters: {
      path: {
        file_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Pause */
  pause_pause_post: {
    parameters: {
      query?: {
        do_pause?: boolean | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": boolean | null;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Next */
  next__next_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Previous */
  previous_previous_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Add */
  add_add__file_id__post: {
    parameters: {
      path: {
        file_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Stop */
  stop_stop_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Clear */
  clear_clear_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Duration */
  duration_duration_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  /** State */
  state_state_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["State"];
        };
      };
    };
  };
  /** Upload File */
  upload_file_file__request_file_id__post: {
    parameters: {
      path: {
        request_file_id: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_file_file__request_file_id__post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": [components["schemas"]["File"], number];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Og Title */
  get_og_title_meta_og_title__website__get: {
    parameters: {
      path: {
        website: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": string | null;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Upload From Url */
  upload_from_url_upload_from_url__request_file_id___website__post: {
    parameters: {
      path: {
        request_file_id: string;
        website: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": [components["schemas"]["File"], number];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete File */
  delete_file_file__file_id__delete: {
    parameters: {
      path: {
        file_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
